# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb7b183819214e36d8e9a2be55af4a8be658f3969e37d1fe98961c1b61e85ff07f16e19071e5036f232ce69cc3748f5e0df2cc3d3f6a9c85e66b85d1bcbb7a95

test:
  secret_key_base: 8ef7d8177437a65d4acff949869f90c646895f85ef7c9d3284c20499690e99fbae5c969d7973d046f8ca5ba254ed9a98d34044839d6e9e8a46dbacaf622091c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
